version: '3.8'

services:

  frontend:
    build:
      context: ./front-end-proof-of-concept/customerDL-validator-FrontEnd

    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./proof-of-concept
    ports:
      - "3031:3031"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: